### PR TITLE
ignore failing test

### PR DESCRIPTION
**Pull request by rfqu**
the whole build failed because of one test com.rultor.agents.daemons.StartsDaemonITCase. With the test excluded, build passes on both maven 3.2.1 and 3.3.3.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@rfqu Thanks for the pull request, let me find a reviewer..

**Comment by alex-palevsky** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rfqu we can't just ignore the test. At least, we should add a puzzle to it, in order to motivate others to fix the problem in the future. If we just ignore, nobody will be fixing it... See http://www.yegor256.com/2009/03/04/pdd.html

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid now and should be closed.

Quote from [here](https://github.com/yegor256/rultor/issues/704#issuecomment-165954872):

> The build fails because of a failing test. Pull request #965 created which excludes this test. Bug #966 created to fix this test. I believe I am done with this issue.

https://github.com/yegor256/rultor/issues/966 turned out to not be a bug anyways, #704 that this is supposed to provide a temporary "solution" for and is associated with this is invalid too.

**Comment by original-brownbear** [comment]
@yegor256 could you please close this one?

**Comment by original-brownbear** [comment]
@alex-palevsky this is invalid.

**Comment by yegor256** [comment]
@original-brownbear closed

**Comment by original-brownbear** [comment]
@yegor256 thanks!

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is invalid now and should be closed.
> 
> Quote from [here](https://github.com/yegor256/rultor/issues/704#issuecomment-165954872):
> 
> > The build fails because of a failing test. Pull request #965 created which excludes this test. Bug #966 created to fix this test. I believe I am done with this issue.
> 
> https://github.com/yegor256/rultor/issues/966 turned out to not be a bug anyways, #704 that this is supposed to provide a temporary "solution" for and is associated with this, is invalid too.
> 

@original-brownbear "invalid" label already at this task

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is invalid.

@original-brownbear "invalid" label already at this ticket

**Pull request closed without merging**
