### PR TITLE
feat(#1682): Specify a release title

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
This pull request implements the feature for setting a release title. Once merged, we will be able to use Rultor in the following way:
```
@rultor release, tag is `1.5`, title is `Version 1.5.0`
```

Closes: #1682

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.75.0`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!

**Pull request merged**
