### PR TITLE
Remove @todo puzzle from source code - Issue #681

### PR DESCRIPTION
**Pull request by Marczeeee**
Issue #681

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Thanks, let me find someone who can review this pull request

**Comment by alex-palevsky** [comment]
@carlosmiranda hlp us to review this

**Comment by carlosmiranda** [comment]
@Marczeeee There are some Checkstyle errors in your build. Please run `mvn clean install -Pqulice` and ensure that the build passes.

**Comment by Marczeeee** [comment]
@carlosmiranda Fixed the problems, Travis build now passes.

**Comment by carlosmiranda** [comment]
@Marczeeee Thanks for the update!

**Comment by carlosmiranda** [comment]
@rultor Try to merge please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by alex-palevsky** [comment]
@carlosmiranda Thanks for your contribution, **16 mins** was added to your account, payment ID is `50350395`; +16 added to your rating, current score is: [+1384](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
