### PR TITLE
#734

### PR DESCRIPTION
**Pull request by maurezen**
Unignored tests.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by alex-palevsky** [comment]
@longtimeago review this PR when possible

**Comment by longtimeago** [comment]
@maurezen You have a checkstyle violation:
```
[ERROR] /src/test/java/com/rultor/agents/github/StarsTest.java[39]: Unused import - org.junit.Test. (UnusedImportsCheck)
```
Please, run ```mvn clean install -Pqulice``` before each push to check that build actually passed

**Comment by maurezen** [comment]
@longtimeago please review the actual pull request. This violation is not in my changes and was not in scope of the original task.

@yegor256 I believe that a separate issue should be created for this, right?

**Comment by yegor256** [comment]
@maurezen I don't think it's possible that a violation is in master. Travis would complain about it.

**Comment by longtimeago** [comment]
@maurezen Actually, violation is in your changes. Same file. And it's caused by removing ```@Test``` annotation but forgetting to remove ```import``` of that annotation

**Comment by maurezen** [comment]
@yegor256 @longtimeago double-checked, you were right, my bad.

@yegor256 I believe I fixed failing check in the master once.

**Comment by longtimeago** [comment]
@maurezen pushed?

**Comment by maurezen** [comment]
@longtimeago fixed just now.

**Comment by maurezen** [comment]
Okay, is not that simple. Created a ticket for that #746.

**Comment by maurezen** [comment]
@longtimeago finally fixed, please review.

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by alex-palevsky** [comment]
@longtimeago thank you, added **19 mins** to your acc, payment num is `50578821`; +19 to your rating, your total score is [+1263](http://www.netbout.com/b/35024?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy

**Pull request merged**
