### PR TITLE
#1209 ConcurrentModificationException in TkTicks

### PR DESCRIPTION
**Pull request by filfreire**
Fixed taking into account info on
https://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by filfreire** [comment]
@yegor256 FYI

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1210` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@filfreire it seems that our master branch is broken, as you can see. One of the integration tests don't pass. I would suggest to create a new ticket, report about the problem there, fix it there in a separate pull request and then get back here and try to merge again.

**Comment by filfreire** [comment]
@yegor256 created issue #1211

**Comment by yegor256** [comment]
@filfreire thanks

**Comment by filfreire** [comment]
@yegor256 FYI, I submitted a PR recently to fix the master branch
https://github.com/yegor256/rultor/pull/1212

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@filfreire let me fix it now in master

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@filfreire hallelujah!

**Comment by filfreire** [comment]
@yegor256 🥇

**Comment by filfreire** [comment]
@yegor256 should I merge master into my branch and submit the merge commit again (so CI runs again) ?

**Comment by yegor256** [comment]
@filfreire feel free to submit new pull requests, sure

**Comment by filfreire** [comment]
Issue is solved. Closing this PR.

**Pull request closed without merging**
