### PR TITLE
Take advantage of new APIs from jcabi-github 0.24

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@cvrebert Thanks for your pull request, let me find someone who can review it

**Comment by alex-palevsky** [comment]
@carlosmiranda review this please

**Comment by cvrebert** [comment]
Travis failure is unrelated:
```
Failed tests: 
  TweetsTest.postsTweet:65 
Argument(s) are different! Wanted:
twitter.post(
    contains("test")
);
-> at com.rultor.agents.twitter.TweetsTest.postsTweet(TweetsTest.java:65)
Actual invocation has different arguments:
twitter.post(
    "Vhmp614iNpBcxPqKEn5c, 1.7 released https://github.com/jeff/Vhmp614iNpBcxPqKEn5c #Java #PHP #Ruby"
);
-> at com.rultor.agents.twitter.Tweets.process(Tweets.java:91)
Tests run: 118, Failures: 1, Errors: 0, Skipped: 10
```

**Comment by carlosmiranda** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@cvrebert oops.. my bad. will try to fix now

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@cvrebert that is actually a bug in your branch. The test fails after you upgrade the version of jcabi-github

**Comment by cvrebert** [comment]
@yegor256 Wacky. I'll investigate.

**Comment by yegor256** [comment]
@cvrebert I fixed it in 155e871

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by cvrebert** [comment]
@yegor256 Removed extraneous `import` and rebased. Please try merging again.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by alex-palevsky** [comment]
@carlosmiranda Many thanks! **16 mins** were added to your account in Transaction ID `60403592` (task took 49 hours and 19 mins). review comments (c=1) added as a bonus. added +16 to your rating, now it is equal to [+3485](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
