### PR TITLE
remove broken link; and cosmetic change

### PR DESCRIPTION
**Pull request by DennyZhang**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1213` is in scope.

**Comment by yegor256** [comment]
@DennyZhang thanks!

**Comment by DennyZhang** [comment]
@yegor256 you're welcome. Cheers.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1213` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1213`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1213` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1213` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1213` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1213` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+210](http://www.0crat.com/u/filfreire).

**Pull request merged**
