### PR TITLE
698:  Implement validation tests based on 2014-07-13-basics.md file

### PR DESCRIPTION
**Pull request by oruam85**
Implement validation tests based on 2014-07-13-basics.md file

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by alex-palevsky** [comment]
@carlosmiranda cuold you review this pull request

**Comment by carlosmiranda** [comment]
@oruam85 I don't think I have comments, thanks for the pull request.

**Comment by carlosmiranda** [comment]
@rultor Mind if we merge now?

**Comment by yegor256** [comment]
@oruam85 were you solving a puzzle? if so, please delete it from the source code

**Comment by oruam85** [comment]
@yegor256 deleted puzzle and add new tests about getAssets method

**Comment by yegor256** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@oruam85 Can you try merging the latest master on this branch? Rultor failed with merge conflict errors.

**Comment by oruam85** [comment]
@carlosmiranda try again please

**Comment by carlosmiranda** [comment]
@rultor Let's try again please.

**Comment by carlosmiranda** [comment]
@rultor Let's try to merge again please

**Comment by yegor256** [comment]
@rultor merge it

**Comment by alex-palevsky** [comment]
@carlosmiranda Much appreciated! **27 mins** was added to your account, payment ID `50305783`... added +27 to your rating, now it is equal to [+1163](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor please deploy

**Pull request merged**
