### PR TITLE
#1211 Fix StartsRequestITCase

### PR DESCRIPTION
**Pull request by filfreire**
Contains previous code developed in PR https://github.com/yegor256/rultor/pull/1208

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1212` is in scope.

**Comment by filfreire** [comment]
@yegor256 I'm not sure of the solution I implemented is the right way to solve the issue.
Kindly CR.

**Comment by yegor256** [comment]
@filfreire I can't reproduce a bug locally. The master is clean for me, after 5a51e1f75f89603e2a45cb661de07dc8ff32d84d. And the change you're making here is not valid. So, I would suggest closing this PR.

**Comment by filfreire** [comment]
Commit https://github.com/yegor256/rultor/commit/aa77b20f1f3fb193fa4c0d4bb00e6e1e51ffbe2f seems to have fixed the issue.

**Pull request closed without merging**
