### PR TITLE
#498 added repo starring

### PR DESCRIPTION
**Pull request by krzyk**

### CODE REVIEW

**Comment by alex-palevsky** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by alex-palevsky** [comment]
@carlosmiranda could you review this pull request

**Comment by carlosmiranda** [comment]
@krzyk , it's a good branch. However, Github is reporting that there are merge conflicts. Please merge with master first.

**Comment by krzyk** [comment]
@carlosmiranda updated

**Comment by carlosmiranda** [comment]
@rultor Would like to merge now.

**Comment by carlosmiranda** [comment]
@krzyk Are you sure you pushed new changes? I don't see any new commits being shown.

**Comment by krzyk** [comment]
@carlosmiranda you are right, I merged to my fork master only :)

**Comment by krzyk** [comment]
@carlosmiranda now it is merged for real

**Comment by carlosmiranda** [comment]
@rultor let's merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by alex-palevsky** [comment]
@carlosmiranda paid, thanks, added **27 mins** to your account, payment `50264815`

+27 to your rating, your total score is [+1017](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
