### PR TITLE
#1197 build number creation explained in the docs

### PR DESCRIPTION
**Pull request by tannakartikey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by tannakartikey** [comment]
@yegor256 seems `rultor merge` succeeded but on Github the PR is still is open

**Comment by yegor256** [comment]
@tannakartikey sometimes it happens. We can't do anything with this. I close it manually.

**Comment by tannakartikey** [comment]
Okay. Thanks.

**Pull request closed without merging**
