### PR TITLE
#1313 Fixed Travis build

### LINKED ISSUE #1313: Travis build is broken
The travis build is failing (branch `master`, commit 5db4123):
https://travis-ci.org/yegor256/rultor/jobs/598137826

Error message:
``` code
Expected feature release number in range of 9 to 14, but got: 8
```

This is a common problem among the Java 8 projects (https://github.com/yegor256/cactoos/issues/1172).

### PR DESCRIPTION
**Pull request by Glusk2**
Closes #1313.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Glusk2 this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by Glusk2** [comment]
Travis build actually passed: https://travis-ci.org/yegor256/rultor/builds/598633425

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1314` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by Glusk2** [comment]
@yegor256
Travis build keeps failing because my proposed fix was to enable Travis builds running on Linux `trusty` with `oraclejdk8`.
But right now Travis builds run on Linux `trusty` with `openjdk8`.

There seem to be further issues in the source code, making the build 
JDK vendor-dependant.

Perhaps a temporary solution is to revert 8d5a150.

**Pull request merged**
