### PR TITLE
Minimize rultor docker image

### PR DESCRIPTION
**Pull request by adarsh-ideal**
Change dockerfile to create a roultor image based on alpine.

### CODE REVIEW

**Comment by adarsh-ideal** [comment]
Can somebody help me to solve travis build fail?

**Comment by alex-palevsky** [comment]
@adarsh-ideal Thanks for your pull request, let me find someone who can review it

**Comment by jayvdb** [comment]
This is an incomplete GCI task, submitted after the end of GCI. So no pressure now. Im on holidays now :)

Im pretty sure there is a missing component, or some component isnt compatible with the Alpine base. TeX is my guess.

**Comment by robbyoconnor** [comment]
@adarsh-ideal I would recommend you run tests locally -- you are currently failing CI.

**Comment by robbyoconnor** [comment]
You may not be able to use alpine for this @adarsh-ideal. I would recommend you do basic research.

**Pull request closed without merging**
