### PR TITLE
#1100 print exceptions when reading profile to shell when ending job

### PR DESCRIPTION
**Pull request by original-brownbear**
#1100 is resolved here

* Catch broken profile exception when ending the talk and print exception message
* Added integration test to check this behaviour

### CODE REVIEW

**Comment by original-brownbear** [comment]
@yegor256 give it a look maybe.
Not perfect, with the printing to the console, but I think this is the safest approach since it still ensures that `end.sh` is ran as long as the container still lives. Otherwise we're left with the busted container for 2h potentially.

**Comment by yegor256** [comment]
@original-brownbear looks good to me. let's merge and release. we're still DOWN!

**Comment by original-brownbear** [comment]
@yegor256 I know. Sorry didn't instantly see your reply, you need to do it though as it is down.
I can't do it, we need to manually merge and release.

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks, someone will review your pull request soon

**Comment by original-brownbear** [comment]
@yegor256 ping?

**Comment by yegor256** [comment]
@original-brownbear merged. deploying...

**Comment by original-brownbear** [comment]
@yegor256 thanks!

**Comment by original-brownbear** [comment]
@yegor256 there's a remaining issue fixing it now 2nd PR incoming ... sorry missed it initially 10-15 min

**Comment by alex-palevsky** [comment]
@rultor deploy now pls

**Pull request merged**
