### PR TITLE
upgrade: nodejs v6 -> nodejs v10

### PR DESCRIPTION
**Pull request by Sammers21**
After this change, rultor will be able to merge the PR: https://github.com/yegor256/npm-files/pull/4

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@Sammers21 done. Now we have to wait 20-30 minutes for Docker Hub to build this new image

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1321` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
