### PR TITLE
Fix of IndexesRequestsTest#retrievesIndexFromSibling failure

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue: https://github.com/yegor256/rultor/issues/733

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by alex-palevsky** [comment]
@carlosmiranda review this pull request plz

**Comment by carlosmiranda** [comment]
@rultor can we merge please?

**Comment by yegor256** [comment]
@dpisarenko maybe we should remove `@Ignore` from the test?

**Comment by dpisarenko** [comment]
@yegor256 Removed it.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dpisarenko** [comment]
FYI: I think the problem with the build is that the tested code returns different results on Windows and Linux. Will try to find out, how to fix it soon.

**Comment by yegor256** [comment]
@dpisarenko yes, that's exactly the problem I reported. in Rultor/Travis everything works fine, while on Mac the test fails. So, I think, the fix can't be that simple.

**Comment by dpisarenko** [comment]
@yegor256 Now the test seems to run, but I ran into another issue: https://github.com/yegor256/rultor/issues/757 .

**Comment by dpisarenko** [comment]
@yegor256 I merged the bugfix #757 . Please review again. Thanks.

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dpisarenko** [comment]
@yegor256 It seems there is a problem with the Internet connection:

```
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: 
https://oss.sonatype.org/content/groups/public/org/apache/tomcat/embed/tomcat-embed-logging-juli/7.0.34/tomcat-embed-logging-juli-7.0.34.pom. Return code is: 500 , ReasonPhrase:Server 
Error.
```

**Comment by yegor256** [comment]
@rultor merge again

**Comment by dpisarenko** [comment]
@yegor256 Now the reason is diffent: Maven tries to access file https://oss.sonatype.org/content/groups/public/com/jcabi/parent/0.32.1/parent-0.32.1-site_en.xml , but it doesn't exist in that directory. `https://oss.sonatype.org/content/groups/public/com/jcabi/parent/0.32.1/` exists, but there is no file `parent-0.32.1-site_en.xml` there. Can this problem be solved by adding another repository?

**Comment by carlosmiranda** [comment]
@yegor256 Maybe the repo wasn't synced yet. Can we try to merge again?

**Comment by dpisarenko** [comment]
@alex-palevsky Waiting for #762 .

**Comment by alex-palevsky** [comment]
> @alex-palevsky Waiting for #762 .

@dpisarenko yep, got it, let's wait for #762 being solved

**Comment by alex-palevsky** [comment]
#762 is closed, we were waiting for it.. maybe we can continue?

**Comment by carlosmiranda** [comment]
@rultor try to merge again please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by alex-palevsky** [comment]
@carlosmiranda thank you, added **17 mins** to your acc, payment num is `52107420`

+17 added to your rating, at the moment it is: [+3157](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
