### PR TITLE
Refactored method

### PR DESCRIPTION
**Pull request by amihaiemil**
Pr for issue #1104 . Removed useless reverse of list and iterated list backwards.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@amihaiemil Let me find a reviewer for this pull request, thanks for submitting it

**Comment by alex-palevsky** [comment]
@original-brownbear the PR is rather short, please review it

**Comment by amihaiemil** [comment]
@rultor merge (it's a test)

**Comment by original-brownbear** [comment]
@amihaiemil please see my comment here https://github.com/yegor256/rultor/issues/1104#issuecomment-222549745 , not gonna merge this sorry .

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks so much! Your account was topped up for **16 mins** (transaction ID is `AP-8P914805VV884282R`, the task took 142 hours and 30 mins). review comments (c=1) added as a bonus. +16 added to your rating, at the moment it is: [+5452](http://www.netbout.com/b/36646?open=rating)

**Pull request closed without merging**
