### PR TITLE
issue #705 update the copyright year

### PR DESCRIPTION
**Pull request by maurezen**
Updated year in copyright context to 2015.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Thanks, let me find someone who can review this pull request

**Comment by alex-palevsky** [comment]
@yegor256 could you review this pull request

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by alex-palevsky** [comment]
@yegor256 Much appreciated! **16 mins** was added to your account, payment ID `000-63b8dd32`

+16 added to your rating, current score is: [+4308](http://www.netbout.com/b/35008?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
