### PR TITLE
#1317 Enables TLSv1.2 on Java 7 builds

### LINKED ISSUE #1317: Enable TLSv1.2 on Java 7 builds
Appveyor and Shippable builds fail.

For example [28311685](https://ci.appveyor.com/project/yegor256/rultor/builds/28311685):

``` ps
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.rultor:rultor:2.0-SNAPSHOT (C:\projects\rultor\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact com.jcabi:parent:pom:0.37.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 35, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Command exited with code 1
```

According to this [SO answer](https://stackoverflow.com/a/50956622) and this [sonatype blog post](https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/) there are two solutions:
``` bash
mvn -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 <goals>
```
or
``` bash
export MAVEN_OPTS=-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
```

### PR DESCRIPTION
**Pull request by Glusk2**
Closes #1317.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Glusk2 this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by Glusk2** [comment]
Appveyor builds now fail with:
``` ps
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.AlwaysFail failed with message:
You should use Unix-like or Mac OS to successfully build Rultor.
                                                With an other OS you are still able to check sources with the command:
                                                'mvn qulice:check -Pqulice'
Always fails!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:00 min
[INFO] Finished at: 2019-10-25T14:08:39+00:00
[INFO] Final Memory: 23M/161M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (fail-on-windows) on project rultor: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Command exited with code 1
```
and Shippable fails with:

``` bash
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2019-10-25T14:12:43+00:00
[INFO] Final Memory: 57M/276M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project rultor: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by yegor256** [comment]
@Glusk2 thanks, merged, let's see

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1318` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
