### PR TITLE
#701 build failed under OS X

### PR DESCRIPTION
**Pull request by maurezen**
added an enforcer rule requiring java of version no less than 1.7

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Many thanks, I'll find someone to review it before we merge

**Comment by alex-palevsky** [comment]
@yegor256 could you review this pull request

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by alex-palevsky** [comment]
@yegor256 **16 mins** added to your account (payment number `000-863c646a`), many thanks for your contribution!. +16 to your rating, your total score is [+4415](http://www.netbout.com/b/35008?open=rating)

**Comment by alex-palevsky** [comment]
@rultor please deploy

**Pull request merged**
