### PR TITLE
#671 updated to latest jcabi-github

### PR DESCRIPTION
**Pull request by krzyk**

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by alex-palevsky** [comment]
@carlosmiranda could you review this pull request

**Comment by carlosmiranda** [comment]
@krzyk Looks good, thanks.

**Comment by carlosmiranda** [comment]
@rultor We should merge now

**Comment by yegor256** [comment]
@rultor merge

**Comment by alex-palevsky** [comment]
@carlosmiranda done, I added **16 mins** in payment `50259355`

+16 added to your rating, current score is: [+941](http://www.netbout.com/b/35023?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
