### PR TITLE
[1207] replace StringUtils usage

### PR DESCRIPTION
**Pull request by pnatashap**
replace StringUtils to Cactoos

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@pnatashap maybe we can also remove `commons-lang` and `commons-text` from the `pom.xml`?

**Comment by pnatashap** [comment]
@yegor256 not yet, there are some more usages

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
