### PR TITLE
replaced oracle-jdk with open-jdk

### PR DESCRIPTION
**Pull request by g4s8**
see https://twitter.com/nixcraft/status/1087769411941851137
images with oracle-jdk may be removed from docker hub

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1292` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
