### PR TITLE
#695: Make the license public on the Maven Site

### PR DESCRIPTION
**Pull request by oruam85**
move the License.txt to the /src/site/resources folder

### CODE REVIEW

**Comment by oruam85** [comment]
this not a solution. the command mvn clean install -Pqulice fail.

**Comment by alex-palevsky** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by alex-palevsky** [comment]
@yegor256 could you review this pull request

**Comment by yegor256** [comment]
@rultor merge

**Comment by alex-palevsky** [comment]
@yegor256 Much appreciated! **17 mins** was added to your account, payment ID `000-5e9871e5`

+17 to your rating, your total score is [+4284](http://www.netbout.com/b/35008?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
