### PR TITLE
Fix build, remove unused declared dependency

### PR DESCRIPTION
**Pull request by filfreire**
Removed unused javax.ws.rs-api dependency.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1208` is in scope.

**Comment by filfreire** [comment]
Travis is failing because the branch it is using is the unmerged master.
Appveyor failure is weird.

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by filfreire** [comment]
@yegor256 Following commit https://github.com/yegor256/rultor/commit/5a51e1f75f89603e2a45cb661de07dc8ff32d84d
did the same as this PR. Closing the PR.

**Pull request closed without merging**
