### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1241` is now in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1241` assigned to @filfreire  ([profile](http://www.0crat.com/u/filfreire})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by yegor256** [comment]
@janczer thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1241` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+555](http://www.0crat.com/u/filfreire).

**Comment by 0crat** [comment]
Payment to ARC for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256, total is [+6670](http://www.0crat.com/u/yegor256).

**Pull request merged**
