### PR TITLE
1302 main branch

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Since `jcabi-github` allows to receive default branch from `Repo`, we can use it instead of hardcoded "master" branch. 

The only thing: I don't know how to test rultor in real life.

Closes: #1302

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could I ask you if you are going to release and deploy a new version of Rultor?
I need that feature [here](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44) and [here](https://github.com/yegor256/rultor/issues/1571)

**Comment by yegor256** [comment]
@volodya-lombrozo deployed

**Comment by volodya-lombrozo** [comment]
@yegor256 It seems that last changes don't help since [the problem](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44#issuecomment-1411979427) remains. In logs I can see, that Rultor still has the same version: `2.0-SNAPSHOT`. Where can I check more logs or info to investigate the problem?

**Pull request merged**
