### PR TITLE
[#1307] json schema for .rultor.yml file

### LINKED ISSUE #1307: Let's create and publish json schema for .rultor.yml
It will be very convenient to me checking my `.rultor.yml ` via some schema, for example in my IDE. Intellij IDEA, for example, has the ability of autocompletion if the schema is present, for example.

Or I can even create a test in my project, that verifies that `.rultor.yml` is valid.

I think that this page: https://doc.rultor.com/reference.html should have a link to such schema.

### PR DESCRIPTION
**Pull request by pnatashap**
Just a schema, it is not use to validate file during the work.
Fix #1307

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@pnatashap just having this file in the repo is useless, I believe. We should link it somewhere. Maybe mention in the documentation, or in README, or both?

**Comment by pnatashap** [comment]
@yegor256 added to readme and link to documentation

**Comment by yegor256** [comment]
@rultor mertge

**Pull request merged**
