### PR TITLE
Support Gradle wrapper

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@valery1707 Thanks for your pull request, let me find someone who can review it

**Comment by alex-palevsky** [comment]
@original-brownbear review this pls (it's a rather short pull request)

**Comment by original-brownbear** [comment]
@valery1707 Hi and thanks for your interest in Rultor!

I see the reasoning behind your suggested change, but I don't think adding this is a good idea for Gradle users or the quality of Rultor. Let me quickly explain why, I'm sure this will help you in using Gradle ( or literally any other thing :) ) on Rultor:

Basically what your suggestion does is make Rultor automatically setup the runner script for Gradle projects, **seemingly** making them work out of the box.
But what you're doing with this is asking Rultor to handle your dependencies for you. 
This is a very bad plan and will cost you a lot of time and nerves in the long run. Your dependencies are your job, you should know about all of them and their versions, not trust your luck and hope those shipping with the Rultor default image will always fit your needs :)

See #1018 for more details on this.

**Comment by original-brownbear** [comment]
@alex-palevsky please close this.

**Comment by valery1707** [comment]
@original-brownbear I trying to add default behavior for `Gradle wrapper` same way as it exists for `Apache Maven`, `Bundler`, `Apache Ant` and `Scala SBT`.
For running `Gradle wrapper` container must contain only JDK, all other things (download and unpack `Gradle`, resolve dependencies, build and test project) will be executed by wrapper exists in project sources.
Version of project dependencies and `Gradle` itself will be resolved by `Gradle wrapper`.

**Comment by original-brownbear** [comment]
@valery1707 I know and really this is more Rultor's fault than your's here for suggesting to do things like the above :) Hence the ticket I linked/created #1018. 

Even if you say that the problem here is small as the wrapper only requires the presence of JDK.
Rultor currently runs on  Java 7, what if we decide to upgrade to 8 eventually?
Your build might break in entirely unexpected ways and think about it ! ;) yes Rultor is open source and in the above scenario you have all the options in the world to track down the issue ... but I can tell you from experience tracking down this kind of stuff takes a lot longer than expected in almost every instance. 
Really, not something you want to get into :)

That being said, personally I'd advise you to do this instead:
You said it yourself, you only need JDK as a dependency and then run that wrapper to install your dependencies right ? :)
So just write that in a Dockerfile and build and push it to Dockerhub along the lines of this:
```
FROM java:7-jdk # Start with Java
COPY gradlew /tmp/gradlew # copy your dependency installer into the image
RUN /tmp/gradlew # install your dependencies
```

then push this to Dockerhub, set it as image in the yml and set the script manually.
Outside of not depending on the official Rultor image to stay compatible with your stuff you also get a much faster and stable build as fewer things will need to be downloaded and installed on every build.

There really is only upsides to keeping things simple here. You know the whole point of Docker is to allow you to create these well defined (and hence extremely simple!) Linux environments.
You're just stealing a lot of time and nerves from yourself by not actively using this to your advantage in your builds.
Even if you've never build a Docker image before in your life, I'm fairly certain figuring out my suggested solution will not take  you more than 20-30 minutes. Think you'll be able to figure out your broken build in the same time when it comes from some subtle change we made to our Dockerfile :) ?

**Comment by valery1707** [comment]
@original-brownbear I understand you point.
I planning to explicit specify Docker image in `.rultor.yml`, and scripts for command too.

In this PR I try add default behavior for Java projects with `Gradle wrapper`. I agree that in some cases it can add some pain to developers who don't worry about configuration of tools they using.

**Comment by original-brownbear** [comment]
@valery1707 
This is getting a little long  :)
but ... last point

>  I agree that in some cases it can add some pain to developers who don't worry about configuration of tools they using.

Exactly that, Rultor is supposed to take some of the human error and resulting uncertainties out of development. Adding more default behavior like this instead of deprecating it, achieves the exact opposite.

=> sorry but this PR goes against the idea of Rultor, frankly one that has a lot more red instead of green in this file would warm my heart at this point .
=> still thanks for the nice exchange, hope I could make a good case here and things came across the right way :)

**Comment by original-brownbear** [comment]
@alex-palevsky please close this :)

**Comment by alex-palevsky** [comment]
> @alex-palevsky please close this.

@original-brownbear closing, as asked

**Comment by alex-palevsky** [comment]
> @alex-palevsky please close this :)

@original-brownbear but it is closed already

**Comment by original-brownbear** [comment]
@alex-palevsky can you handle payment here please and close this for good :) ?

**Comment by alex-palevsky** [comment]
@original-brownbear **21 mins** was added to your account, many thanks for your contribution (payment AP-7V9355931B498823J)! The task took 92 hours and 45 mins.

review comments (c=6) added as a bonus

added +21 to your rating, now it is equal to [+419](http://www.netbout.com/b/36646?open=rating)

**Pull request closed without merging**
