### PR TITLE
Fix qulice License.txt problems on Windows - Issue #752

### PR DESCRIPTION
**Pull request by Marczeeee**
Issue #752

### CODE REVIEW

**Comment by alex-palevsky** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by alex-palevsky** [comment]
@krzyk could you review this pull request

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge this

**Comment by alex-palevsky** [comment]
@krzyk I added **16 mins** to your account, many thanks for working with the project!. added +16 to your rating, now it is equal to [+2785](http://www.netbout.com/b/35035?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy pls

**Pull request merged**
