### PR TITLE
Upgrade dependencies for #946

### PR DESCRIPTION
**Pull request by JimDeanSpivey**
Issue: #946 

Unit tests all ran.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@jimdeanspivey Many thanks, I will find someone to review it before we merge

**Comment by alex-palevsky** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by JimDeanSpivey** [comment]
@yegor256 I opened an issue for this at #994

**Comment by JimDeanSpivey** [comment]
@yegor256 All dependencies have been upgraded. This PR should be good to go.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by JimDeanSpivey** [comment]
@yegor256 I rolledback the `nl.geodienstencentrum.maven:sass-maven-plugin` to its original version `2.14`. This is because rultor is obviously not using maven `3.2.5` or higher, and it built fine for me locally because I am using maven `3.3.9`.

Can we try to merge this again?

**Comment by yegor256** [comment]
@rultor merge

**Comment by original-brownbear** [comment]
@yegor256 I can't close this one yet, but #946 being closed makes this obsolete and it should be closed.

**Comment by yegor256** [comment]
@original-brownbear I close this

**Comment by alex-palevsky** [comment]
@yegor256 thanks, paid, **19 mins** to your account, payment ID is `000-9fe9e3ee`, task took 650 hours and 25 mins to complete

you're getting extra minutes here (c=4)

+19 to your rating, your total score is [+1635](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
