### PR TITLE
#1199 - Replace Guava w/ Cactoos (conflict-free branch)

### PR DESCRIPTION
**Pull request by filfreire**
This is the same diffs from PR #1222 but clean from conflicts for rultor merge stage of the branch.

- Related issue https://github.com/yegor256/rultor/issues/1199

/cc @yegor256

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#1246](https://github.com/yegor256/rultor/issues/1246) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@yegor256 kindly CR and merge, if possible.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#1246](https://github.com/yegor256/rultor/issues/1246) is now out of scope

**Comment by 0pdd** [comment]
@filfreire the puzzle [#1303](https://github.com/yegor256/rultor/issues/1303) is still not solved.

**Comment by 0pdd** [comment]
@filfreire the puzzle [#2155](https://github.com/yegor256/rultor/issues/2155) is still not solved; solved: [#1303](https://github.com/yegor256/rultor/issues/1303).

**Pull request merged**
