### PR TITLE
#1238 - Bump year on copyright

### PR DESCRIPTION
**Pull request by filfreire**
/cc @yegor256

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1239` is now in scope.

**Comment by filfreire** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 please follow-up this PR.

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 I fixed the checkstyle violations. You can retry merging.

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 strange, rultor merged, but the PR is still left open... opened issue #1243 to follow-up on this behavior. Closing this PR.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1239` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#1239](https://github.com/yegor256/rultor/issues/1239) is now out of scope

**Pull request closed without merging**
