### PR TITLE
#1100 illegal print from shell fixed

### LINKED ISSUE #1100: Invalid rultor.yml has caused a system outage
Related to Issue #1032

### PR DESCRIPTION
**Pull request by original-brownbear**
#1100 is dealt with again here.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@yegor256 one second writing test but this solution is kinda obvious ... sorry for missing this in the other PR :/

**Comment by alex-palevsky** [comment]
@original-brownbear Thanks, someone will review your pull request soon

**Comment by alex-palevsky** [comment]
@original-brownbear it's a very short pull request coming from the architect, there won't be any code review

**Comment by original-brownbear** [comment]
@yegor256 I removed the call to that code now, pragmatic solution ok today?

**Comment by yegor256** [comment]
@original-brownbear merged and deployed

**Comment by original-brownbear** [comment]
@yegor256 thanks!, seems working again

**Pull request merged**
