### PR TITLE
Fix small typo in README

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@valery1707 Many thanks, I will find someone to review it before we merge

**Comment by alex-palevsky** [comment]
@original-brownbear pull request is rather short, review it please

**Comment by yegor256** [comment]
@valery1707 thanks!

**Comment by alex-palevsky** [comment]
@original-brownbear I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by alex-palevsky** [comment]
@rultor deploy now pls

**Pull request merged**
