### PR TITLE
#950 Reverting How Rultor Works

### PR DESCRIPTION
**Pull request by gumbelmj**
#950 This change has already been merged into the master branch of Rultor. I'm reverting the changes so we can try the merge again.

### CODE REVIEW

**Comment by gumbelmj** [comment]
@caarlos0 Here's a new pull request on a branch not named Master.

**Comment by alex-palevsky** [comment]
@gumbelmj Many thanks, I will find someone to review it before we merge

**Comment by alex-palevsky** [comment]
@mkordas review this pull request please

**Comment by caarlos0** [comment]
@gumbelmj if the changes were already merge, I guess you can just inform in the parent issue that you're done...

**Comment by mkordas** [comment]
@gumbelmj where is your fork gone?

**Comment by mkordas** [comment]
@gumbelmj moreover, please refer to both PRs in issue

**Comment by gumbelmj** [comment]
@mkordas  PR #991 is the other pull request.  I removed the fork after @caarlos0 suggested that I just close the pull request.  The changes have been merged into master.  You can see "How Rultor Works" is updated here: https://github.com/yegor256/rultor/  So there's nothing here to show as changed.

**Comment by mkordas** [comment]
@gumbelmj but @caarlos0 suggested to just close PR, did he say anything about deleting fork?

**Comment by gumbelmj** [comment]
@mkordas correct, but there was nothing in the fork or the pull request.  I revert the change and added back the correct text just so there was 'something' to review, but realized it was pointless.

**Comment by mkordas** [comment]
@gumbelmj OK, but fork should be deleted usually only when you don't plan to contribute for this repository anymore and you have all PRs merge. Otherwise it could stay.

**Comment by alex-palevsky** [comment]
@mkordas I just added **19 mins** to your account, many thanks for your contribution (56cf30c87dd1744b740002c3).. 19 hours and 27 mins spent here

review comments (c=4) added as a bonus

added +19 to your rating, now it is equal to [+7195](http://www.netbout.com/b/36080?open=rating)

**Pull request closed without merging**
