### PR TITLE
687

### PR DESCRIPTION
**Pull request by wentwog**
This PL is expected to solve only 
```
Caused by: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/DP118M/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
    at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
    at com.jcabi.xml.XMLDocument.<clinit>(XMLDocument.java:84)
```
issue.
There are other issues and the build fill fail.
For these other issues I'm going to create separate github issues.

### CODE REVIEW

**Comment by alex-palevsky** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by wentwog** [comment]
1) Snap CI build failed because some connection issues
```
java.io.IOException: com.jcraft.jsch.JSchException: java.net.ConnectException: Connection refused
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:306)
	at com.jcabi.ssh.SSH.exec(SSH.java:192)
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:103)
	at com.rultor.agents.daemons.ArchivesDaemon.process(ArchivesDaemon.java:94)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.agents.daemons.ArchivesDaemonITCase.archivesDaemon(ArchivesDaemonITCase.java:95)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at com.jcraft.jsch.Util$1.run(Util.java:362)
	at java.lang.Thread.run(Thread.java:745)
```
so, I suppose it's a build env config issue and is unrelated to the current fix - maube we need to create new ticket for this ?

2) Builds failed on Shippable  - can't see the log

3) The build failed on Semaphore that's interesting.
The fail is not at the the unit test stage as was before, but now at iteration test stage - I'm investigating the issue.

**Comment by alex-palevsky** [comment]
@yegor256 could you review this pull request

**Comment by yegor256** [comment]
@rultor let's try to merge

**Comment by wentwog** [comment]
@yegor256 I've updated this PL and now I've fixed the aforementioned integration tests issue too. 
Let's review and merge.

Now 4 checks  are successful.
2 failing because of different issues:
1) Snap CI - connection refused - I suppose it's config issue of the particular builder.
2)  AppVeyor - it has Windows OS and failing because of #708.

Also I've updated from master branch, so the merge should pass (unless new changes appear to the master branch).

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by alex-palevsky** [comment]
@yegor256 thanks, I just added **25 mins** to your account, payment `000-8ca91480`. added +25 to your rating, now it is equal to [+4399](http://www.netbout.com/b/35008?open=rating)

**Comment by alex-palevsky** [comment]
@rultor deploy now pls

**Pull request merged**
