### PR TITLE
feat(#1237): verify Pull Requests Check Runs before merging   

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Added verification of check runs before merging pull requests.

Closes: #1237

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/jcabi/jcabi-github/pull/1622

**Comment by yegor256** [comment]
@volodya-lombrozo I released a new version

**Comment by yegor256** [comment]
@rultor release, tag is `1.75.0`

**Comment by volodya-lombrozo** [comment]
@yegor256 Looks like it works :) https://github.com/volodya-lombrozo/hg-revision-plugin/pull/17#issuecomment-1482364951

**Pull request merged**
