### PR TITLE
Renovate/aws java sdk monorepo and others

### PR DESCRIPTION
**Pull request by pnatashap**
- update dependencies
- setup a version for maven-surefire-plugin (can be a reason for merge fail)
- removed junit4 dependency and all the tests migrated
- try to update qulice-maven-plugin, but too many diffs in style, keep as is
- RandomUtil is now deprecated, change it to SecureRandom to do not use additional library (but recommended lib is https://commons.apache.org/proper/commons-rng/index.html)

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look
sorry, it is big

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by pnatashap** [comment]
@yegor256 this part of the exception is not enough to understand where is the problem. Could paste more?

**Comment by pnatashap** [comment]
@yegor256  If I understand correctly, the problem is missing gemfile or folder with libs

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@pnatashap thanks a lot!

**Pull request merged**
