### PR TITLE
 #1203 - fix Illegal character at TkAuth

### PR DESCRIPTION
**Pull request by filfreire**
Related to issue https://github.com/yegor256/rultor/issues/1203
@yegor256 FYI

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1229` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 merged with master, with the latest correction to puzzle (https://github.com/yegor256/rultor/commit/4f68b94e29ee15c4d5289b367ac0fc5875c5a99c)

please try to merge again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256, I merged latest `master` branch with this one and locally qulice check is passing. Can you try to merge again?

**Comment by yegor256** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 closing this PR since the code is merged.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1229` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#1229](https://github.com/yegor256/rultor/issues/1229) is now out of scope

**Pull request closed without merging**
