### PR TITLE
feat(#1657): redundant message

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Don't print redundant message if some checks were failed.

Closes: #1657

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@volodya-lombrozo I think we should fix the bug first: https://github.com/yegor256/rultor/issues/1659

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, I see. I'm working on it https://github.com/yegor256/rultor/issues/1661

**Pull request merged**
