### PR TITLE
#992, removed appveyor badge and appveyor config file

### PR DESCRIPTION
**Pull request by original-brownbear**
#992 is solved by this, Rultor cannot build on Appveyor: 
* removing the references to it from the readme and the Appveyor config file

### CODE REVIEW

**Comment by original-brownbear** [comment]
@alex-palevsky no need for CR here, see https://github.com/yegor256/rultor/issues/992 ... this just needs input from @yegor256

**Comment by alex-palevsky** [comment]
@original-brownbear Many thanks for the PR, let me find a reviewer for it

**Comment by alex-palevsky** [comment]
@pinaf review this please

**Comment by original-brownbear** [comment]
@alex-palevsky please see my comment above no need for a reviewer here!

The "code" change is  entirely trivial but needs feedback by @yegor256 in the linked ticket #992 .

**Comment by pinaf** [comment]
@original-brownbear if you are the architect you can just ask alex to mark this as invalid and no payment will be made.

**Comment by original-brownbear** [comment]
@alex-palevsky please mark this as invalid *but* assign @yegor256 as we need his and only his input here.

**Comment by original-brownbear** [comment]
@pinaf thanks and sorry for the confusion!

**Comment by pinaf** [comment]
@original-brownbear send alex 2 separate commands
```
@alex-palevsky this issue is invalid
```
```
@alex-palevsky please assign @yegor256
```

**Comment by original-brownbear** [comment]
@alex-palevsky this issue is invalid

**Comment by original-brownbear** [comment]
@alex-palevsky please assign @yegor256

**Comment by original-brownbear** [comment]
Closing since the associated issue was closed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky please mark this as invalid *but* assign @yegor256 as we need his and only his input here.

@original-brownbear too many tasks (11) are active in the project already, can't assign new ones

**Comment by alex-palevsky** [comment]
> @alex-palevsky this issue is invalid

@original-brownbear right, I added "invalid" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky please assign @yegor256

@original-brownbear too many tasks (11) are active in the project already, can't assign new ones

**Pull request closed without merging**
