### PR TITLE
Fix QnVersion reply phase

### LINKED ISSUE #1154: Bug in QnVersion reply phase
Then generating response to command `version` rultor make incorrect link to commit:
> My current version is 1.62.3, Git revision is [`ef166fc7f`](https://github.com/yegor256/rultor/commit/1.62.3)

Real example: https://github.com/valery1707/jcommander-ext/issues/2#issuecomment-295822793

I prepare PR with fix

### PR DESCRIPTION
**Pull request by valery1707**
Fix #1154

### CODE REVIEW

**Comment by valery1707** [comment]
AppVeyor is always fail after 9300cfea07c951f6ad3a11830e2bd3456ddcfe81

**Comment by valery1707** [comment]
Codacy, as I think, check for only JUnit asserts, but test actually use Hamcrest asert

**Comment by valery1707** [comment]
TravisCI terminate build docker image by timeout - is it my problem?

**Comment by valery1707** [comment]
@yegor256 need I fix Codacy and AppVeyor build?

**Comment by alex-palevsky** [comment]
@valery1707 Thanks, someone will review your pull request soon

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@valery1707 thanks!

**Pull request closed without merging**
