### PR TITLE
feat(#1661): print first line of a GitHub comment

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Print first line of the error message.

Closes: #1661

### CODE REVIEW

**Comment by yegor256** [comment]
@volodya-lombrozo I didn't understand, what did you change in this PR? You only added the unit test and reformatted the code a bit, but no functionality was changed. Am I wrong?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo I didn't understand, what did you change in this PR? You only added the unit test and reformatted the code a bit, but no functionality was changed. Am I wrong?

@yegor256 Was:
```
"We failed, sorry, try again:\n\n```%[exception]s```"
```
Become:
```
"We failed, sorry, try again:\n\n```\n%[exception]s\n```"
```

The trick in the first line of the code block that indicates the language is used.

**Comment by volodya-lombrozo** [comment]
I was trying to emphasise that in the test

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
