### PR TITLE
921 - mark release as latest

### PR DESCRIPTION
**Pull request by maurezen**
Pr for #921 - Added an override for `pre` property default value

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@maurezen Thanks for the pull request, let me find a reviewer..

**Comment by alex-palevsky** [comment]
@pinaf could you review this pull request

**Comment by pinaf** [comment]
@maurezen is there an issue for this? what's the idea of the PR?

**Comment by maurezen** [comment]
@pinaf oops, forgot to mention original issue. Yes, it's a pr for #921

**Comment by pinaf** [comment]
@maurezen I suppose the logic is already in place and you just changed the default value?

**Comment by maurezen** [comment]
@pinaf yes, see https://github.com/yegor256/rultor/issues/921#issuecomment-133389923

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by pinaf** [comment]
@yegor256 this was merged but the github PR doesn't reflect it and I didn't get credit for it. Could you please investigate?

**Comment by pinaf** [comment]
@yegor256 please take a look at this issue - the PR was merged but not closed.

**Comment by yegor256** [comment]
@pinaf this pull request doesn't solve the problem reported in #921 :) The author is asking us to implement an ability to mark releases as "final". He is not talking about rultor releases. It's a totally invalid PR

**Comment by pinaf** [comment]
@yegor256 I see, thanks.

**Pull request closed without merging**
